### ISSUE TITLE
Poorly named functions

### ISSUE THREAD

**Issue by eilims** [aleks-trifonova/COMP-222-Performance-Metrics-#1]
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L9
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L36
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L54
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L67

Rename these functions to something more appropriate!

**Comment by aleks-trifonova** [comment]
I cannot he specified that we shouldn't rename the options in our code.  
"Do not modify the choices (1,2,3,4,5) or the test script used for grading your
assignment will not work correctly, and will cause a significant penalty in your total
score. It will not be re-graded to accommodate your modified choices." This is directly from the assignment specifications
