### ISSUE TITLE
Initialize Variables

### ISSUE THREAD

**Issue by eilims** [aleks-trifonova/COMP-222-Performance-Metrics-#2]
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L11
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L39
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L70
https://github.com/aleks-trifonova/COMP-222-Performance-Metrics-/blob/a019bc9a5c871a6ca4b79c9cdb1f0d20daa6c646/AleksTrifonova-asmt-1.c#L71

Uninitialized variables have undefined behavior on different systems. Make sure they are all initialized to something.

**Comment by eilims** [comment]
Also global variables should be initialized as well!

**Comment by aleks-trifonova** [comment]
I am not too sure what to initliaze them to, otherwise I would have.

**Comment by eilims** [comment]
You can init them to 0. Just don't leave them blank.

**Comment by aleks-trifonova** [comment]
Okay I will do that. Thank you for the help.
